driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04
    driver:
      gui: false
      provision: true
      vagrantfiles:
        - test/provision/vagrant_debian.rb
  - name: windows-2012r2
    driver:
      gui: false
      box:  mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[atom]
  - name: apm
    run_list:
      - recipe[atom::packages]
    attributes:
      atom:
        packages:
          - vim-mode
    # having issues getting apm to run via test-kitchen on Windows
    excludes: windows-2012r2

verifier:
  name: inspec
